// <auto-generated />
using System;
using HRV7.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRV7.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190509135826_ViewModelNewRequisition")]
    partial class ViewModelNewRequisition
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HRV7.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BereavementDays");

                    b.Property<DateTime>("DateOfHire");

                    b.Property<string>("Department")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<int>("SickDays");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<int>("VacationDays");

                    b.HasKey("EmployeeId");

                    b.ToTable("AllEmployees");
                });

            modelBuilder.Entity("HRV7.Models.Requisition", b =>
                {
                    b.Property<int>("RequisitionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateRequested");

                    b.Property<string>("EmpNote");

                    b.Property<int>("EmployeeFK");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("MgrNote");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("Status");

                    b.Property<string>("TimeOffType")
                        .IsRequired();

                    b.Property<int>("TotalDays");

                    b.HasKey("RequisitionId");

                    b.ToTable("AllRequisitions");
                });

            modelBuilder.Entity("HRV7.Models.ViewModelNewRequisition", b =>
                {
                    b.Property<int>("ViewModelNewRequisitionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("VMNREmpEmployeeId");

                    b.Property<int?>("VMNRReqRequisitionId");

                    b.HasKey("ViewModelNewRequisitionId");

                    b.HasIndex("VMNREmpEmployeeId");

                    b.HasIndex("VMNRReqRequisitionId");

                    b.ToTable("EmployeeRequisitionInformation");
                });

            modelBuilder.Entity("HRV7.Models.ViewModelNewRequisition", b =>
                {
                    b.HasOne("HRV7.Models.Employee", "VMNREmp")
                        .WithMany()
                        .HasForeignKey("VMNREmpEmployeeId");

                    b.HasOne("HRV7.Models.Requisition", "VMNRReq")
                        .WithMany()
                        .HasForeignKey("VMNRReqRequisitionId");
                });
#pragma warning restore 612, 618
        }
    }
}
